"""
Django settings for UN_accounting_system project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=None):
    value = os.environ.get(name, '')
    items = [item.strip() for item in value.split(',') if item.strip()]
    return items if items else (default or [])


def _is_placeholder_host(value):
    """Ignore example values from .env.example that break production CSRF."""
    lowered = value.lower()
    return 'your-app.up.railway.app' in lowered or lowered.startswith('example.')


def _csrf_origins_for_hosts(hosts):
    origins = []
    for host in hosts:
        if not host or _is_placeholder_host(host):
            continue
        if host.startswith('.'):
            origins.append(f'https://*{host}')
        else:
            origins.append(f'https://{host}')
    return origins


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-7f39$@4^t34h!bq%yp()kcgh90e65scn52xsuexmoceu-c+$2k',
)

# SECURITY WARNING: don't run with debug turned on in production!
_on_railway = bool(os.environ.get('RAILWAY_ENVIRONMENT') or os.environ.get('RAILWAY_PUBLIC_DOMAIN'))
DEBUG = _env_bool('DEBUG', default=not _on_railway)

ALLOWED_HOSTS = [
    h for h in _env_list('ALLOWED_HOSTS') if not _is_placeholder_host(h)
]
_railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '').strip()
if _railway_domain and _railway_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_railway_domain)
if _on_railway and '.railway.app' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('.railway.app')
if not ALLOWED_HOSTS and not DEBUG:
    ALLOWED_HOSTS = ['.railway.app']

CSRF_TRUSTED_ORIGINS = [
    o for o in _env_list('CSRF_TRUSTED_ORIGINS') if not _is_placeholder_host(o)
]
if _railway_domain:
    _railway_origin = f'https://{_railway_domain}'
    if _railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_railway_origin)
if _on_railway:
    for origin in _csrf_origins_for_hosts(['.railway.app']):
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)
for origin in _csrf_origins_for_hosts(ALLOWED_HOSTS):
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)


# Application definition

INSTALLED_APPS = [
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.MustChangePasswordMiddleware',
]

ROOT_URLCONF = 'UN_accounting_system.urls'

# CRISPY CONFIG
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.branding',
            ],
        },
    },
]

WSGI_APPLICATION = 'UN_accounting_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_database_url = os.environ.get('DATABASE_URL', '').strip()

if _on_railway and not _database_url:
    raise RuntimeError(
        'DATABASE_URL is not set. On Railway: open your app service → Variables → '
        'Add Reference → PostgreSQL → DATABASE_URL, then redeploy.'
    )

if _database_url:
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=False,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

SITE_BASE_URL = os.environ.get('SITE_BASE_URL', '').strip()
if not SITE_BASE_URL and _railway_domain:
    SITE_BASE_URL = f'https://{_railway_domain}'

RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '').strip()
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', default=True)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@projectaccounting.local')
SYSTEM_ADMIN_EMAIL = os.environ.get('SYSTEM_ADMIN_EMAIL', '').strip()

_smtp_configured = bool(EMAIL_HOST_USER and EMAIL_HOST_PASSWORD)
EMAIL_CONFIGURED = bool(RESEND_API_KEY or _smtp_configured)
if os.environ.get('EMAIL_BACKEND'):
    EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND')
elif RESEND_API_KEY:
    EMAIL_BACKEND = 'accounts.email_backends.ResendEmailBackend'
elif _smtp_configured:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
elif DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'accounts.email_backends.UnconfiguredEmailBackend'

if _on_railway and not RESEND_API_KEY and not _smtp_configured and not DEBUG:
    import logging
    logging.getLogger(__name__).warning(
        'Email not configured on Railway — set RESEND_API_KEY or EMAIL_HOST_USER/EMAIL_HOST_PASSWORD '
        'and DEFAULT_FROM_EMAIL so onboarding invites can be sent.'
    )

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

# Local `manage.py test` uses syncdb (no migrations) so SQLite test DB avoids
# legacy migration FK issues; Railway/Postgres production is unchanged.
import sys


class _DisableMigrations:
    def __contains__(self, item):
        return True

    def __getitem__(self, item):
        return None


if 'test' in sys.argv:
    MIGRATION_MODULES = _DisableMigrations()