# Generated by Django 5.2.13 on 2026-05-02 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank_account_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('contact_address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GLAnalysisCategory',
            fields=[
                ('category_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, null=True, unique=True)),
                ('is_modal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('stock_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBuildCategory',
            fields=[
                ('build_cat_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('project_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierAccount',
            fields=[
                ('supplier_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('contact_address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('gl_account_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('debit_credit', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=2)),
                ('description', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('analysis_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.glanalysiscategory')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('modules', models.ManyToManyField(blank=True, to='accounts.module')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('contact_address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('access_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usercategory')),
            ],
        ),
    ]
