# Generated by Django 5.2.13 on 2026-05-05 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBuilding',
            fields=[
                ('building_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTaskBudget_actuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BOMTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_raised', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('build_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.projectbuildcategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.product')),
                ('project_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.projecttask')),
            ],
        ),
        migrations.CreateModel(
            name='LPOTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpo_no', models.CharField(max_length=50, unique=True)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('variance_explanation', models.TextField(blank=True, help_text='Required if quote is not the lowest')),
                ('stars', models.IntegerField(default=0)),
                ('build_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.projectbuildcategory')),
                ('project_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.projecttask')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.projectbuilding')),
            ],
        ),
        migrations.CreateModel(
            name='GRNTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(max_length=50, unique=True)),
                ('delivery_note_ref', models.CharField(max_length=100)),
                ('qty_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lpo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.lpotransaction')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_order_no', models.CharField(max_length=50, unique=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHQ', 'Cheque'), ('MPESA', 'M-Pesa')], max_length=10)),
                ('is_confirmed_by_director', models.BooleanField(default=False)),
                ('date_confirmed', models.DateTimeField(blank=True, null=True)),
                ('grn', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.grntransaction')),
                ('source_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='RFQTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_no', models.CharField(max_length=50, unique=True)),
                ('quote_ref', models.CharField(blank=True, max_length=100)),
                ('unit_cost_quoted', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('bom_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bomtransaction')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.supplieraccount')),
            ],
        ),
        migrations.AddField(
            model_name='lpotransaction',
            name='selected_quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.rfqtransaction'),
        ),
    ]
