# Generated by Django 5.2.13 on 2026-05-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_projectbuilding_projecttaskbudget_actuals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='code',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_modal',
        ),
        migrations.RemoveField(
            model_name='module',
            name='url',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
