# Generated by Django 5.2.13 on 2026-05-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_module_code_remove_module_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='staff_no',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='Employee Staff Number'),
            preserve_default=False,
        ),
    ]
