# Generated by Django 5.2.13 on 2026-05-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bomheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomheader',
            name='status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar_id', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uom', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.bomheader')),
            ],
        ),
    ]
