# Generated by Django 5.2.13 on 2026-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_bomheader_status_bomitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqtransaction',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload winning quote PDF for UN audit compliance', null=True, upload_to='quotes/%Y/%m/'),
        ),
    ]
