# Generated by Django 5.2.13 on 2026-05-10 15:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rfqtransaction_supporting_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ro_no', models.CharField(max_length=50, unique=True)),
                ('date_raised', models.DateTimeField(auto_now_add=True)),
                ('technical_requirement_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SIGNED', 'Signed')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.useraccount')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ros', to='accounts.projecttask')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('uom', models.CharField(max_length=20)),
                ('tech_spec_summary', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product')),
                ('ro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.requisitionorder')),
            ],
        ),
        migrations.AddIndex(
            model_name='requisitionorder',
            index=models.Index(fields=['ro_no'], name='accounts_re_ro_no_7aaeda_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitionorder',
            index=models.Index(fields=['task'], name='accounts_re_task_id_7497ee_idx'),
        ),
    ]
