# Generated by Django 5.2.13 on 2026-05-10 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_requisitionorder_requisitionorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomheader',
            name='ro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='accounts.requisitionorder'),
        ),
    ]
