# Generated by Django 5.2.13 on 2026-05-24 08:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_bomheader_ro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscRequisitionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mro_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_sourcing', models.BooleanField(default=True)),
                ('funding_status', models.CharField(choices=[('PENDING', 'Pending'), ('LOCKED', 'Locked'), ('DISBURSED', 'Disbursed'), ('RECONCILED', 'Reconciled')], default='PENDING', max_length=20)),
                ('messenger_name', models.CharField(default='Mr. Omambo', max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='misc_requisitions', to='accounts.projecttask')),
            ],
        ),
        migrations.CreateModel(
            name='MiscPurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_sourcing', models.BooleanField(default=False)),
                ('funding_status', models.CharField(choices=[('PENDING', 'Pending'), ('LOCKED', 'Locked'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=20)),
                ('mpo_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('messenger_name', models.CharField(default='Mr. Omambo', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.projecttask')),
            ],
        ),
        migrations.CreateModel(
            name='MiscPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gl_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.glaccount')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.projecttask')),
                ('mpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.miscpurchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='CashClearingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cleared', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disbursement_method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('MPESA', 'M-Pesa'), ('OTHER', 'Other')], max_length=20)),
                ('other_method_details', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_description', models.TextField(help_text='Details of the payment/transaction')),
                ('cleared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_clearing', to=settings.AUTH_USER_MODEL)),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.glaccount')),
                ('mpo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='clearing_record', to='accounts.miscpurchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='MPOStatusRegistry',
            fields=[
                ('mro_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status_registry', serialize=False, to='accounts.miscrequisitionorder')),
                ('is_sourcing', models.BooleanField(default=False)),
                ('funding_status', models.CharField(max_length=20)),
                ('task_code', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_sourcing', 'funding_status', 'task_code'], name='accounts_mp_is_sour_06e422_idx')],
            },
        ),
    ]
