# Generated by Django 5.2.13 on 2026-05-24 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_miscrequisitionorder_miscpurchaseorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_label', models.CharField(max_length=100)),
                ('material_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('labour_burden', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('misc_reserve', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_authorized_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='accounts.projecttask')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MATERIAL', 'Material Total Cost'), ('LABOUR', 'Labour Burden'), ('MISC', 'Misc / Logistics Reserve')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.projectbudget')),
            ],
        ),
    ]
