# Generated by Django 5.2.13 on 2026-05-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_projectbudget_budgettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpotransaction',
            name='awarded_by_office',
            field=models.CharField(default='Main Office', max_length=255),
        ),
        migrations.AddField(
            model_name='lpotransaction',
            name='delivery_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lpotransaction',
            name='supplier_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lpotransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lpotransaction',
            name='lpo_no',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
