# Generated by Django 5.2.13 on 2026-05-31 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_lpotransaction_awarded_by_office_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_no', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.lpotransaction')),
            ],
        ),
    ]
