# Generated by Django 5.2.13 on 2026-06-01 14:09

import django.db.models.deletion
from django.db import migrations, models


def _drop_fks_to(cursor, table):
  cursor.execute(
    """
    SELECT conrelid::regclass::text, conname
    FROM pg_constraint
    WHERE contype = 'f'
      AND confrelid = %s::regclass
    """,
    [table],
  )
  for rel_table, conname in cursor.fetchall():
    cursor.execute(f'ALTER TABLE {rel_table} DROP CONSTRAINT IF EXISTS "{conname}"')


def _add_constraint_if_missing(cursor, conname, sql):
  cursor.execute(
    "SELECT 1 FROM pg_constraint WHERE conname = %s",
    [conname],
  )
  if not cursor.fetchone():
    cursor.execute(sql)


def _column_udt_name(cursor, table, column):
  cursor.execute(
    """
    SELECT udt_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = %s
      AND column_name = %s
    """,
    [table, column],
  )
  row = cursor.fetchone()
  return row[0] if row else None


def _table_exists(cursor, table):
  cursor.execute(
    """
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = %s
    """,
    [table],
  )
  return cursor.fetchone() is not None


def _column_exists(cursor, table, column):
  return _column_udt_name(cursor, table, column) is not None


def _convert_varchar_fk_to_int(cursor, table, column, ref_table, ref_match_column):
  """Replace a varchar FK with integer id via temp column (no USING subquery)."""
  if not _table_exists(cursor, table):
    return
  if _column_udt_name(cursor, table, column) == "int4":
    return

  temp_col = f"{column}_new_int"
  cursor.execute(f"ALTER TABLE {table} ALTER COLUMN {column} DROP NOT NULL")
  cursor.execute(
    f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {temp_col} integer"
  )
  cursor.execute(
    f"""
    UPDATE {table} AS t
    SET {temp_col} = r.id
    FROM {ref_table} AS r
    WHERE r.{ref_match_column} = t.{column}
    """
  )
  cursor.execute(f"ALTER TABLE {table} DROP COLUMN {column}")
  cursor.execute(f"ALTER TABLE {table} RENAME COLUMN {temp_col} TO {column}")


def forwards_pk_changes(apps, schema_editor):
  """PostgreSQL-safe PK migration; drops dependent FKs before PK changes."""
  if schema_editor.connection.vendor != "postgresql":
    return

  with schema_editor.connection.cursor() as cursor:
    _drop_fks_to(cursor, "accounts_projectbuildcategory")

    cursor.execute(
      "ALTER TABLE accounts_projectbuildcategory "
      "DROP CONSTRAINT IF EXISTS accounts_projectbuildcategory_pkey"
    )
    cursor.execute(
      """
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_schema = 'public'
            AND table_name = 'accounts_projectbuildcategory'
            AND column_name = 'id'
        ) THEN
          ALTER TABLE accounts_projectbuildcategory ADD COLUMN id SERIAL;
        END IF;
      END $$
      """
    )
    _add_constraint_if_missing(
      cursor,
      "accounts_projectbuildcategory_pkey",
      "ALTER TABLE accounts_projectbuildcategory ADD PRIMARY KEY (id)",
    )
    _add_constraint_if_missing(
      cursor,
      "accounts_projectbuildcategory_build_cat_id_key",
      "ALTER TABLE accounts_projectbuildcategory "
      "ADD CONSTRAINT accounts_projectbuildcategory_build_cat_id_key "
      "UNIQUE (build_cat_id)",
    )

    for table in ("accounts_bomtransaction", "accounts_lpotransaction"):
      _convert_varchar_fk_to_int(
        cursor,
        table,
        "build_category_id",
        "accounts_projectbuildcategory",
        "build_cat_id",
      )

    _drop_fks_to(cursor, "accounts_projectbuilding")

    cursor.execute(
      "ALTER TABLE accounts_projectbuilding "
      "DROP CONSTRAINT IF EXISTS accounts_projectbuilding_pkey"
    )
    cursor.execute(
      """
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_schema = 'public'
            AND table_name = 'accounts_projectbuilding'
            AND column_name = 'id'
        ) THEN
          ALTER TABLE accounts_projectbuilding ADD COLUMN id SERIAL;
        END IF;
      END $$
      """
    )
    cursor.execute(
      """
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_schema = 'public'
            AND table_name = 'accounts_projectbuilding'
            AND column_name = 'building_code'
        ) THEN
          ALTER TABLE accounts_projectbuilding
          ADD COLUMN building_code varchar(50);
        END IF;
      END $$
      """
    )
    if _column_exists(cursor, "accounts_projectbuilding", "building_id"):
      cursor.execute(
        "UPDATE accounts_projectbuilding "
        "SET building_code = building_id "
        "WHERE building_code IS NULL AND building_id IS NOT NULL"
      )
    cursor.execute(
      "UPDATE accounts_projectbuilding "
      "SET building_code = 'UNKNOWN' "
      "WHERE building_code IS NULL"
    )
    cursor.execute(
      "ALTER TABLE accounts_projectbuilding "
      "ALTER COLUMN building_code SET NOT NULL"
    )
    _add_constraint_if_missing(
      cursor,
      "accounts_projectbuilding_pkey",
      "ALTER TABLE accounts_projectbuilding ADD PRIMARY KEY (id)",
    )
    _add_constraint_if_missing(
      cursor,
      "accounts_projectbuilding_building_code_key",
      "ALTER TABLE accounts_projectbuilding "
      "ADD CONSTRAINT accounts_projectbuilding_building_code_key "
      "UNIQUE (building_code)",
    )

    if _table_exists(cursor, "accounts_lpotransaction"):
      match_col = (
        "building_id"
        if _column_exists(cursor, "accounts_projectbuilding", "building_id")
        else "building_code"
      )
      _convert_varchar_fk_to_int(
        cursor,
        "accounts_lpotransaction",
        "building_id",
        "accounts_projectbuilding",
        match_col,
      )

    cursor.execute(
      "ALTER TABLE accounts_projectbuilding "
      "DROP COLUMN IF EXISTS building_id"
    )

    if _table_exists(cursor, "accounts_bomtransaction"):
      _add_constraint_if_missing(
        cursor,
        "accounts_bomtransaction_build_category_id_fkey",
        "ALTER TABLE accounts_bomtransaction "
        "ADD CONSTRAINT accounts_bomtransaction_build_category_id_fkey "
        "FOREIGN KEY (build_category_id) REFERENCES accounts_projectbuildcategory (id) "
        "DEFERRABLE INITIALLY DEFERRED",
      )
    if _table_exists(cursor, "accounts_lpotransaction"):
      _add_constraint_if_missing(
        cursor,
        "accounts_lpotransaction_build_category_id_fkey",
        "ALTER TABLE accounts_lpotransaction "
        "ADD CONSTRAINT accounts_lpotransaction_build_category_id_fkey "
        "FOREIGN KEY (build_category_id) REFERENCES accounts_projectbuildcategory (id) "
        "DEFERRABLE INITIALLY DEFERRED",
      )
      _add_constraint_if_missing(
        cursor,
        "accounts_lpotransaction_building_id_fkey",
        "ALTER TABLE accounts_lpotransaction "
        "ADD CONSTRAINT accounts_lpotransaction_building_id_fkey "
        "FOREIGN KEY (building_id) REFERENCES accounts_projectbuilding (id) "
        "DEFERRABLE INITIALLY DEFERRED",
      )


def backwards_pk_changes(apps, schema_editor):
  if schema_editor.connection.vendor != "postgresql":
    return
  # Fresh Railway deploys do not need a reverse path.


class Migration(migrations.Migration):

  dependencies = [
    ("accounts", "0014_lpoitem"),
  ]

  operations = [
    migrations.RemoveField(
      model_name="lpotransaction",
      name="selected_quote",
    ),
    migrations.AddField(
      model_name="lpotransaction",
      name="supplier",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.PROTECT,
        to="accounts.supplieraccount",
      ),
    ),
    migrations.SeparateDatabaseAndState(
      database_operations=[
        migrations.RunPython(forwards_pk_changes, backwards_pk_changes),
      ],
      state_operations=[
        migrations.AlterField(
          model_name="projectbuildcategory",
          name="build_cat_id",
          field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
          model_name="projectbuildcategory",
          name="id",
          field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
          model_name="projectbuilding",
          name="building_id",
        ),
        migrations.AddField(
          model_name="projectbuilding",
          name="building_code",
          field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
          model_name="projectbuilding",
          name="id",
          field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
          model_name="lpotransaction",
          name="build_category",
          field=models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.PROTECT,
            to="accounts.projectbuildcategory",
          ),
        ),
        migrations.AlterField(
          model_name="lpotransaction",
          name="building",
          field=models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.PROTECT,
            to="accounts.projectbuilding",
          ),
        ),
      ],
    ),
  ]
