# Generated by Django 5.2.13 on 2026-06-06 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_miscpurchaseorder_submitted_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbudget',
            name='equipment_reserve',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Equipment hire or purchase allocation', max_digits=15),
        ),
        migrations.AlterField(
            model_name='budgettransaction',
            name='category',
            field=models.CharField(choices=[('MATERIAL', 'Material Total Cost'), ('LABOUR', 'Labour Burden'), ('MISC', 'Misc / Logistics Reserve'), ('MAINTENANCE', 'Office Maintenance & Ops'), ('EQUIPMENT', 'Equipment Hire / Purchase')], max_length=20),
        ),
        migrations.AlterField(
            model_name='miscpurchaseorder',
            name='funding_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('LOCKED', 'Locked'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='budget_type',
            field=models.CharField(blank=True, choices=[('RFQ_LPO', 'Project Budget (RFQ_LPO)'), ('ADHOC_MISC', 'Ad-Hoc Budget (ADHOC_MISC)')], default='RFQ_LPO', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskDisbursementPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=50, unique=True)),
                ('budget_line', models.CharField(choices=[('MATERIAL', 'Payment of Goods'), ('MAINTENANCE', 'Office Maintenance & Ops'), ('LABOUR', 'Labour'), ('EQUIPMENT', 'Equipment Hire / Purchase')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('payee', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHQ', 'Cheque'), ('MPESA', 'M-Pesa')], default='BANK', max_length=10)),
                ('aie_reference', models.CharField(blank=True, default='', help_text='CEO AIE authority reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_payments', to='accounts.projecttask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
