# Generated by Django 5.2.13 on 2026-06-06 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_task_disbursement_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbudget',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo_approved_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='ceo_aie_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='is_ceo_approved',
            field=models.BooleanField(default=False, help_text='CEO AIE lock — line figures read-only after approval'),
        ),
        migrations.CreateModel(
            name='CEOFundRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('release_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transfer_method', models.CharField(default='BANK', max_length=20)),
                ('from_office', models.CharField(default='CEO Office — Authority to Incur Expenditure (AIE)', max_length=200)),
                ('to_officer', models.CharField(default='GM — Accounting Officer', max_length=200)),
                ('bank_reference', models.CharField(blank=True, default='', max_length=100)),
                ('aie_memo_ref', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo_fund_releases', to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_releases', to='accounts.projectbudget')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_releases', to='accounts.projecttask')),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
    ]
