# Generated by Django 5.2.13 on 2026-06-06 18:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_ceo_budget_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='grntransaction',
            name='invoice_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='grntransaction',
            name='receipt_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='grntransaction',
            name='received_by_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lpotransaction',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lpotransaction',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='grntransaction',
            name='delivery_note_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='grntransaction',
            name='grn_no',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='grntransaction',
            name='lpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='accounts.lpotransaction'),
        ),
        migrations.AlterField(
            model_name='grntransaction',
            name='qty_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.grntransaction')),
                ('lpo_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_lines', to='accounts.lpoitem')),
            ],
            options={
                'unique_together': {('grn', 'lpo_item')},
            },
        ),
    ]
