# Generated by Django 5.2.13 on 2026-06-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_lpo_grn_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='grntransaction',
            name='supplier_rep_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
