# Generated by Django 5.2.13 on 2026-06-07 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_grn_supplier_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='cheque_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='payment_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='prepared_by_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='transfer_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='grn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_voucher', to='accounts.grntransaction'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='pay_order_no',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_method',
            field=models.CharField(choices=[('BANK', 'Bank Transfer'), ('CHQ', 'Cheque'), ('CASH', 'Cash'), ('MPESA', 'M-Pesa')], max_length=10),
        ),
    ]
