# Generated by Django 5.2.13 on 2026-06-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_adhoc_officer_voucher_line_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(default='Project Accounting', max_length=120)),
                ('app_short_name', models.CharField(default='Project Accounting', max_length=80)),
                ('app_tagline', models.CharField(blank=True, default='Financial Operations Platform', max_length=200)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'verbose_name': 'Software settings',
                'verbose_name_plural': 'Software settings',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=80)),
                ('contact_address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('tax_pin', models.CharField(blank=True, default='', max_length=50)),
                ('document_tagline', models.CharField(blank=True, default='Operations Command', max_length=200)),
                ('is_default', models.BooleanField(default=False, help_text='Used on printed vouchers, memos, and official documents.')),
            ],
            options={
                'ordering': ['org_code'],
            },
        ),
        migrations.AlterField(
            model_name='adhocofficerpaymentvoucher',
            name='officer_name',
            field=models.CharField(help_text='Receiving / purchasing officer', max_length=255),
        ),
    ]
