# Generated by Django 5.2.13 on 2026-06-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_app_settings_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='registered_address',
            field=models.TextField(blank=True, default='', help_text='Registered / postal address (optional).'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_address',
            field=models.TextField(blank=True, default='', help_text='Contact / office address shown on documents.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Full legal name, e.g. Pioneer Contactors Co Ltd', max_length=200),
        ),
    ]
