# Generated by Django 5.2.13 on 2026-06-10 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_organization_registered_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Client company this user belongs to (e.g. Pioneer, Company B).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Platform fallback when a user has no company assigned.'),
        ),
    ]
