# Generated by Django 6.0.6 on 2026-06-20 14:48

import django.db.models.deletion
from django.db import migrations, models


def seed_access_roles(apps, schema_editor):
    UserCategory = apps.get_model("accounts", "UserCategory")
    roles = [
        ("USER_ADMIN", "User Admin (Global)", 100, "Creates and onboards users, assigns access categories."),
        ("REGULAR_USER", "Regular User", 10, "GRN by email, sources items/services, Misc PO approved notifications."),
        ("SENIOR_SITE_MANAGER", "Senior Site Manager", 30, "Prepares and authorises BOM and RO; LPO/GRN confirmation."),
        ("GENERAL_MANAGER", "General Manager", 50, "Approves payments, bid evaluation; signatory document copies."),
        ("CEO", "CEO", 80, "Budget approval, fund disbursement, variance alerts, CC on all emails."),
    ]
    for code, description, rank, summary in roles:
        UserCategory.objects.update_or_create(
            code=code,
            defaults={"description": description, "rank": rank, "role_summary": summary},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_bomheader_items_locked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategory',
            options={'ordering': ['-rank', 'description']},
        ),
        migrations.AddField(
            model_name='useraccount',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='User must set password via onboarding link before full access.'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='onboarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarded_users', to='accounts.useraccount'),
        ),
        migrations.AddField(
            model_name='usercategory',
            name='code',
            field=models.CharField(blank=True, help_text='Stable role key, e.g. SENIOR_SITE_MANAGER.', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usercategory',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0, help_text='Higher rank = more senior (used for display ordering).'),
        ),
        migrations.AddField(
            model_name='usercategory',
            name='role_summary',
            field=models.TextField(blank=True, default='', help_text='Short summary of responsibilities for admin reference.'),
        ),
        migrations.AlterField(
            model_name='bomheader',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_TO_GM', 'Sent to GM'), ('AWARDED', 'Awarded'), ('GENERATED', 'Generated from RO')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='bomheader',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_headers', to='accounts.projecttask'),
        ),
        migrations.RunPython(seed_access_roles, migrations.RunPython.noop),
    ]
