# Generated by Django 6.0.6 on 2026-06-27 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_useraccount_onboarding_email_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocofficerpaymentvoucher',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Linked employee registry record for control-account posting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_vouchers', to='accounts.useraccount'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='ledger_gl_account',
            field=models.ForeignKey(blank=True, help_text='Linked GL control account for this bank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_ledgers', to='accounts.glaccount'),
        ),
        migrations.AddField(
            model_name='glaccount',
            name='account_role',
            field=models.CharField(blank=True, choices=[('CEO_DISBURSEMENT', 'CEO Disbursement Account'), ('GM_OPERATING', 'GM Operating / Expense Account'), ('SUPPLIER_CONTROL', 'Supplier Control'), ('EMPLOYEE_CONTROL', 'Employee Control')], default='', help_text='System role for fund-control accounts.', max_length=30),
        ),
        migrations.AddField(
            model_name='supplieraccount',
            name='control_gl_account',
            field=models.ForeignKey(blank=True, help_text='Supplier sub-ledger control account for GM payments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_controls', to='accounts.glaccount'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='control_gl_account',
            field=models.ForeignKey(blank=True, help_text='Employee advance control account for GM cash/M-Pesa disbursements.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_controls', to='accounts.glaccount'),
        ),
        migrations.CreateModel(
            name='GLLedgerPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posting_type', models.CharField(choices=[('CEO_TO_GM', 'CEO to GM transfer'), ('OFFICER_ADVANCE', 'Employee advance'), ('SUPPLIER_PAYMENT', 'Supplier payment'), ('GM_EXPENSE', 'GM expense payment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_gl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_credits', to='accounts.glaccount')),
                ('debit_gl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_debits', to='accounts.glaccount')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_postings', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_postings', to='accounts.projecttask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adhocofficerpaymentvoucher',
            name='ledger_posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_vouchers', to='accounts.glledgerposting'),
        ),
        migrations.AddField(
            model_name='ceofundrelease',
            name='ledger_posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_releases', to='accounts.glledgerposting'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='ledger_posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to='accounts.glledgerposting'),
        ),
        migrations.CreateModel(
            name='LedgerControlSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('ceo_disbursement_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.bankaccount')),
                ('ceo_disbursement_gl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.glaccount')),
                ('gm_operating_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.bankaccount')),
                ('gm_operating_gl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.glaccount')),
            ],
            options={
                'verbose_name': 'Ledger control settings',
                'verbose_name_plural': 'Ledger control settings',
            },
        ),
    ]
