# Generated by Django 6.0.6 on 2026-06-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_ledger_fund_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbudget',
            name='review_status',
            field=models.CharField(blank=True, choices=[('PROVISION', 'Provisional — not sent to CEO'), ('WITH_CEO', 'With CEO — awaiting review'), ('RETURNED', 'Returned to GM'), ('APPROVED', 'CEO approved (AIE locked)'), ('RELEASED', 'Funds released to GM')], default='PROVISION', max_length=20),
        ),
    ]
