# Generated by Django 6.0.6 on 2026-06-28 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_budget_review_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbudget',
            name='last_return_reason',
            field=models.TextField(blank=True, default='', help_text='Latest CEO reason when budget was returned to GM.'),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='review_status',
            field=models.CharField(blank=True, choices=[('PROVISION', 'Provisional — not sent to CEO'), ('WITH_CEO', 'With CEO — awaiting confirmation'), ('RETURNED', 'Returned to GM for correction'), ('APPROVED', 'CEO confirmed (AIE locked)'), ('RELEASED', 'Funds released to GM')], default='PROVISION', max_length=20),
        ),
        migrations.CreateModel(
            name='BudgetReviewEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('GM_SUBMIT', 'GM submitted budget to CEO'), ('GM_RESUBMIT', 'GM resubmitted after CEO return'), ('CEO_RETURN', 'CEO returned budget to GM'), ('CEO_APPROVE', 'CEO approved and locked budget (AIE)'), ('CEO_RELEASE', 'CEO released funds to GM')], max_length=20)),
                ('memo_subject', models.CharField(blank=True, default='', max_length=200)),
                ('memo_body', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('from_officer', models.CharField(blank=True, default='', max_length=200)),
                ('to_officer', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to='accounts.projectbudget')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_review_events', to=settings.AUTH_USER_MODEL)),
                ('source_mpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_review_events', to='accounts.miscpurchaseorder')),
                ('source_mro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_review_events', to='accounts.miscrequisitionorder')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_review_events', to='accounts.projecttask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
