# Generated by Django 6.0.6 on 2026-07-18 10:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_useraccount_partial_bid_access_ended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='misccompletionrecord',
            options={'verbose_name': 'Misc Completion Record', 'verbose_name_plural': 'Misc Completion Records'},
        ),
        migrations.AlterModelOptions(
            name='miscvariation',
            options={'ordering': ['ref'], 'verbose_name': 'Misc Variation', 'verbose_name_plural': 'Misc Variations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='accounting_officer_name',
            field=models.CharField(blank=True, default='', help_text="Accounting Officer / head of the entity, e.g. 'Eng Charles Korir'.", max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='accounting_officer_title',
            field=models.CharField(blank=True, default='', help_text="Title of the accounting officer, e.g. 'Principal Secretary'.", max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='profile_summary',
            field=models.TextField(blank=True, default='', help_text="About / mandate shown on the sponsor's public landing page."),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Official website shown on the sponsor landing page.'),
        ),
        migrations.AlterField(
            model_name='budgetreviewevent',
            name='action',
            field=models.CharField(choices=[('GM_SUBMIT', 'GM submitted budget to CEO'), ('GM_RESUBMIT', 'GM resubmitted after CEO return'), ('GM_REMIND', 'GM sent CEO budget approval reminder (desk on hold)'), ('CEO_RETURN', 'CEO returned budget to GM'), ('CEO_APPROVE', 'CEO approved and locked budget (AIE)'), ('CEO_RELEASE', 'CEO released funds to GM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='misccompletionrecord',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, help_text='Total actual spend confirmed from receipts.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='misccompletionrecord',
            name='completed_by',
            field=models.ForeignKey(help_text='Senior Engineer who physically inspects and signs off the work.', on_delete=django.db.models.deletion.PROTECT, related_name='misc_completions_signed', to='accounts.useraccount'),
        ),
        migrations.AlterField(
            model_name='misccompletionrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='misccompletionrecord',
            name='photo_1',
            field=models.ImageField(help_text='Required: photograph of completed work (before/after preferred).', upload_to='misc_completions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='misccompletionrecord',
            name='quality_notes',
            field=models.TextField(blank=True, default='', help_text='Punch list, quality observations, or follow-up required.'),
        ),
        migrations.AlterField(
            model_name='misccompletionrecord',
            name='scope_achieved',
            field=models.TextField(help_text='Plain-English description of what was physically completed.'),
        ),
        migrations.AlterField(
            model_name='misccompletionrecord',
            name='variance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='actual_cost minus budget_ceiling. Negative = underspend (good).', max_digits=15),
        ),
        migrations.AlterField(
            model_name='miscvariation',
            name='actual_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Actual cost from MiscCompletionRecord. Set at reconciliation.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='miscvariation',
            name='approved_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='CEO-approved ceiling. Set at time of approval.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='miscvariation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='miscvariation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'CEO Approved'), ('ACTIVE', 'Active — work in progress'), ('RECONCILED', 'Reconciled — GL closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15),
        ),
        migrations.AlterField(
            model_name='miscvariation',
            name='variation_type',
            field=models.CharField(default='MISC_SELF_EXECUTE', editable=False, help_text='Always MISC_SELF_EXECUTE. Type A subcontract variations use execution.VariationOrder.', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_status',
            field=models.CharField(choices=[('PENDING', 'Pending confirmation'), ('ACTIVE', 'Active')], default='ACTIVE', help_text='Pending until platform admin approves a new subscriber registration.', max_length=20),
        ),
    ]
