# Generated by Django 5.x on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_alter_misccompletionrecord_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="contractor_type",
            field=models.CharField(
                choices=[
                    ("BUILDING", "Building contractor"),
                    ("ROADS", "Roads contractor"),
                    ("TELECOM", "Telecom infrastructure contractor"),
                    ("CONSULTANT", "Consultant"),
                ],
                default="BUILDING",
                help_text="Primary contractor category for onboarding and document defaults.",
                max_length=20,
            ),
        ),
    ]
