# Generated by Django 6.0.6 on 2026-08-07 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_miscpurchaseitem_source_bom_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username_attempted', models.CharField(blank=True, db_index=True, max_length=150)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], db_index=True, default='failed', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=400)),
                ('path', models.CharField(blank=True, default='', max_length=200)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login audit event',
                'verbose_name_plural': 'Login audit events',
                'ordering': ['-created_at'],
            },
        ),
    ]
