# Generated by Django 6.0.6 on 2026-08-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_login_audit_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginauditevent',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loginauditevent',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='loginauditevent',
            name='geo_source',
            field=models.CharField(blank=True, default='ip', help_text='How location was resolved (ip).', max_length=20),
        ),
        migrations.AddField(
            model_name='loginauditevent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='loginauditevent',
            name='location_label',
            field=models.CharField(blank=True, default='', help_text='Approximate place from IP (city / region / country).', max_length=200),
        ),
        migrations.AddField(
            model_name='loginauditevent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='loginauditevent',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
